src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'cards')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: 'string', length: 16)]
    #[Assert\NotBlank]
    private ?string $number = null;

    #[ORM\Column(type: 'string', length: 5)]
    #[Assert\NotBlank]
    private ?string $expirationDate = null;

    #[ORM\Column(type: 'string', length: 3)]
    #[Assert\NotBlank]
    private ?string $cvv = null;

    // Getters and Setters

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getExpirationDate(): ?string
    {
        return $this->expirationDate;
    }

    public function setExpirationDate(string $expirationDate): self
    {
        $this->expirationDate = $expirationDate;

        return $this;
    }

    public function getCvv(): ?string
    {
        return $this->cvv;
    }

    public function setCvv(string $cvv): self
    {
        $this->cvv = $cvv;

        return $this;
    }

    public function getLastDigits(): string
    {
        return substr($this->number, -4); // Supposez que $this->number contient le numéro complet de la carte
    }

}

templates/partials/cardForm.html.twig
{% if isProfilePage %}
    {% set confirm_button = "confirm"%}
    {% set delete_button = "card-delete-button"%}
    {% set total_price = "" %}

{% else %}
    {% set confirm_button = "Payer"%}
    {% set delete_button = "Payer"%}
    {% set total_price = totalPrice|number_format(2, ',', ' ') %}
{% endif %}

<div class="user-info" data-section="carte">
    <div class="form-title">                            
        <span>{{'payment-title' | trans}}</span>
    </div>
    {% if cardsWithForms is not empty and cardsWithForms is defined %}
        {% for item in cardsWithForms %}
            {% set card = item.card %}
            {% set form = item.form %}
            <!-- Option de paiement par carte {{ loop.index }} -->
            <div class="payment-option" id="card-payment-option-{{ loop.index }}">
                <input type="checkbox" id="card-payment-{{ loop.index }}" class="payment-checkbox">
                <label for="card-payment-{{ loop.index }}" class="payment-label">
                    {{'payment-label' | trans }} {{ card.lastDigits }}
                </label>
            </div>

            <!-- Formulaire de paiement par carte {{ loop.index }} -->
            <div class="payment-form-container" id="card-payment-form-{{ loop.index }}" style="display: none;">
                <div class="payment-title">
                    <h2> {{'payment-label' | trans }}{{ card.lastDigits }}</h2>
                </div>
                {{ form_start(form, {'attr': {'id': 'cardForm-' ~ loop.index}}) }}
                    <label class="payment-label" for="card-number-{{ loop.index }}">{{'card-number' | trans}}</label>
                    {{ form_widget(form.number, {'attr': {'id': 'card-number-' ~ loop.index, 'readonly': true, 'value': 'XXXX-XXXX-XXXX-' ~ card.lastDigits}}) }}
                    
                    <!-- Champ caché pour transmettre l'ID de la carte -->
                    <input type="hidden" name="card_id" value="{{ card.id }}">
                                
                    <label class="payment-label" for="expiry-date-{{ loop.index }}">{{'card-date' | trans}}</label>
                    {{ form_widget(form.expirationDate, {'attr': {'id': 'expiry-date-' ~ loop.index, 'readonly': true, 'value': card.expirationDate}}) }}
                                
                    <label class="payment-label" for="cvv-{{ loop.index }}">CVV</label>
                    <div class="cvv-wrapper">
                        {{ form_widget(form.cvv, {'attr': {'id': 'cvv-' ~ loop.index, 'placeholder': '', 'value': ''}}) }}
                        <button class="delete-card-btn" data-card-id="{{ card.id }}" type="submit" data-csrf-token="{{ csrf_token('delete-card') }}">
                            <span id="total-price">{{delete_button | trans}} - {{total_price}} €</span>
                            <i class="bx bx-right-arrow-alt"></i>
                        </button>
                    </div>
                {{ form_end(form) }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="payment-option" id="card-payment-option-add">
        <input type="checkbox" id="card-payment-add" class="payment-checkbox">
        <label for="card-payment-add" class="payment-label">
            {{'payment-add-title' | trans}}
        </label>
    </div>

    <!-- Formulaire d'ajout paiement par carte -->
    <div class="payment-form-container" id="card-payment-form-add" style="display: none;">
        <div class="payment-title">
            <h2>{{'payment-add-title' | trans}}</h2>
        </div>
        {{ form_start(addCardForm, {'attr': {'id': 'addCardForm'}}) }}
            <label class="payment-label" for="card-number-add">{{'card-number' | trans}}</label>
            {{ form_widget(addCardForm.number, {'attr': {'id': 'card-number-add', 'placeholder': 'card-number-placeholder' | trans, 'name': 'number'}}) }}
       
            <label class="payment-label" for="expiry-date-add">{{'card-date' | trans}}</label>
            {{ form_widget(addCardForm.expirationDate, {'attr': {'id': 'expiry-date-add', 'placeholder': 'card-date-placeholder' | trans, 'name': 'expiration_date'}}) }}

            <label class="payment-label" for="cvv-add">CVV</label>
            <div class="cvv-wrapper">
                {{ form_widget(addCardForm.cvv, {'attr': {'id': 'cvv-add', 'placeholder': 'cvv', 'name': 'cvv'}}) }}
                <button class="input-submit" type="submit">
                    <span id="confirm">{{confirm_button | trans}} - {{total_price}} €</span>
                    <i class="bx bx-right-arrow-alt"></i>
                </button>
            </div>
        {{ form_end(addCardForm) }}
    </div>

templates/partials/footer.html.twig
{# templates/partials/footer.html.twig #}
<style>
    .lang {
        position: fixed;
        bottom: 10px;
        right: 10px;
        z-index: 1000;
    }

    .lang .list {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    .list a {
        color: #FFF;
        text-decoration: none;
        font-family: 'Poppins'
    }

    .list a:hover {
        text-decoration: underline;
    }
</style>

<footer>
    <div class="lang">
        <ul class="list">
            <li><a href="{{ path('app_change_language', { 'lang': 'fr' }) }}">Français</a></li>
            <li><a href="{{ path('app_change_language', { 'lang': 'en' }) }}">English</a></li>
        </ul>
    </div>
</footer>

templates/partials/header.html.twig
<style>
    .cart-container {
        position: relative;
        display: inline-block;
        align-self: center;  /* Assure que l'élément est centré verticalement par rapport à son conteneur */
    }

    .cart-count {
        position: absolute;
        top: -5px; /* Ajuste légèrement la position verticale */
        right: 10px; /* Ajuste la position horizontale */
        background-color: red;
        color: white;
        font-size: 14px;
        font-weight: bold;
        border-radius: 50%;
        padding: 2px 6px;
        min-width: 18px;
        height: 18px;
        line-height: 18px; /* Centre verticalement le texte */
        text-align: center;
        display: flex;
        justify-content: center; /* Centrage horizontal */
        align-items: center; /* Centrage vertical */
    }

    .icon {
        font-size: 28px; /* Taille de l'icône ajustée pour un meilleur alignement */
        vertical-align: middle; /* S'assure que l'icône soit correctement centrée avec les autres éléments */
    }

    .banner {
        background-color: #888ffd;
        padding: 20px;
        position: fixed;
        left: 0;
        top: 0;
        right: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        z-index: 1000;
        font-family: 'Poppins', sans-serif;
    }

    .banner a {
        display: flex;
        align-items: center;
    }

    .banner h1 {
        margin: 0;
        font-size: 30px;
        color: #000;
    }

    .login-link {
        color: #000;
        font-size: 18px;
        text-decoration: none;
        background-color: #888ffd;
        padding: 10px 20px;
        border-radius: 15px;
        transition: background-color 0.3s ease;
        margin-left: auto;
        border: 1px solid #b0b5ff;
        margin-right: 20px;
    }

    .login-link:hover {
        background-color: #b0b5ff;
    }

    .pp {
        margin-left: 20px;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        transition: transform 0.3s ease;
    }

    .pp:hover {
        transform: scale(1.05);
    }

    .logo {
        width: 50px;
        height: auto;
        margin-right: 15px;
    }

    .a:hover {
        background-color: #888ffd;
    }

</style>

<header>
    <div class="banner">
        <a class="home" href="/home">
            <img src="{{ asset('styles/img/logo.jpg') }}" alt="Logo Manga Mania" class="logo">
            <h1><strong>MANGA MANIA</strong></h1>
        </a>
        {% if user %}
            <!-- Si admin, affiche le panneau de configuration -->
            {% if user.role == true %}
                <a class="login-link" href="/admin-pannel">{{'config-pannel'| trans}}</a>
            {% else %}
                <a class="login-link a" style="border: none;"></a>
            {% endif %}
                <div class="cart-container">
                    <a class="login-link" href="/cart">
                        <i class="fa-solid fa-basket-shopping icon"></i>
                        <span id="cart-count" class="cart-count">0</span>
                    </a>
                </div>


            <!-- Si l'user possède une photo de profil, sinon affiche default.png -->
            <a href="/profile">
                {% if user.profilePicture %}
                    <img class ="pp" src="{{ asset(user.profilePicture.path) }}">
                {% else %}
                    <img class ="pp" src="{{ asset('pp/default.png') }}">
                {% endif %}
            </a>

        {% else %}
            <a class="login-link" href="/login-register">{{ 'login_button' | trans }}</a>
        {% endif %} 
    </div>
</header>

templates/partials/notifications.html.twig
    <style>
        .notification {
            position: fixed;
            top: 30px;
            right: 20px;
            z-index: 2000;
        }

        .login_success {
            --color: #bf0a0a;
        }

        .first_login {
            -- color: #e5ad00;
        }

        .success {
            --color: #10ae00;
        }

        .error {
            --color: #e50000;
        }

        .toast {
            position: relative;
            padding: 10px;
            color: #fff;
            margin-bottom: 10px;
            width: 400px;
            display: grid;
            grid-template-columns: 70px 1fr 70px;
            border-radius: 5px;
            background-image:
                linear-gradient(to right, var(--color), #21264D 20%);
            animation: show 0.3s ease 1 forwards;
            font-family: 'Poppins'
        }

        .toast i {
            color: var(--color);
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: x-large;
        }

        .toast .title {
            font-size: x-large;
            font-weight: bold;
        }

        .toast span,
        .toast i:nth-child(3) {
            color: #fff;
            opacity: 0.6;
            font-size: 14px;
        }

        @keyframes show {
            0% {
                transform: translateX(100%);
            }

            40% {
                transform: translateX(-5%);
            }

            80% {
                transform: translateX(0%);
            }

            100% {
                transform: translateX(-10%);
            }
        }

        .toast::before {
            position: absolute;
            bottom: 0;
            left: 0;
            background-color: var(--color);
            width: 100%;
            height: 3px;
            content: '';
            box-shadow: 0 0 10px var(--color);
            animation: timeOut 5s linear 1 forwards
        }

        @keyframes timeOut {
            to {
                width: 0;
            }
        }

        #cross:hover {
            cursor: pointer;
        }
    </style>
    
    <div class="notification"></div>
    {% if error %}
        <script>
            let notifications = document.querySelector('.notification');
            function createToast(type, icon, title, text) {
                let newToast = document.createElement('div');
                newToast.innerHTML = `
                    <div class="toast ${type}">
                        <i class="${icon}"></i>
                        <div class="content">
                            <div class="title">${title}</div>
                            <span>${text}</span>
                        </div>
                        <i id ="cross" class="fa-solid fa-xmark" onclick="this.parentElement.remove()"></i>
                    </div>`;
                notifications.appendChild(newToast);
                newToast.timeOut = setTimeout(() => newToast.remove(), 5000);
            }

            let type = 'error'; 
            let icon = 'fa-solid fa-circle-xmark'; 
            let title = "{{ 'error_title' | trans }}"; 
            let text = "{{ 'error_text' | trans }}"; 

            createToast(type, icon, title, text);
        </script>
    {% endif %}
    {% if registerSuccess %}
        <script>
        let notifications = document.querySelector('.notification');
        function createToast(type, icon, title, text) {
            let newToast = document.createElement('div');
            newToast.innerHTML = `
                <div class="toast ${type}">
                    <i class="${icon}"></i>
                    <div class="content">
                        <div class="title">${title}</div>
                        <span>${text}</span>
                    </div>
                    <i id ="cross" class="fa-solid fa-xmark" onclick="this.parentElement.remove()"></i>
                </div>`;
            notifications.appendChild(newToast);
            newToast.timeOut = setTimeout(() => newToast.remove(), 5000);
        }

        let type = 'success'; 
        let icon = 'fa-solid fa-circle-check'; 
        let title = "{{ 'account_created_title' | trans }}"; 
        let text = "{{ 'account_created_text' | trans }}"; 

        createToast(type, icon, title, text);
        </script>
    {% endif %}
    {% if mailExist %}
        <script>
            let notifications = document.querySelector('.notification');
            function createToast(type, icon, title, text) {
                let newToast = document.createElement('div');
                newToast.innerHTML = `
                    <div class="toast ${type}">
                        <i class="${icon}"></i>
                        <div class="content">
                            <div class="title">${title}</div>
                            <span>${text}</span>
                        </div>
                        <i id ="cross" class="fa-solid fa-xmark" onclick="this.parentElement.remove()"></i>
                    </div>`;
                notifications.appendChild(newToast);
                newToast.timeOut = setTimeout(() => newToast.remove(), 5000);
            }

            let type = 'error'; 
            let icon = 'fa-solid fa-circle-xmark'; 
            let title = "{{ 'mailExist_title' | trans }}"; 
            let text = "{{ 'mailExist_text' | trans }}"; 

            createToast(type, icon, title, text);
        </script>
    {% endif %}
    {% if nameExist %}
        <script>
            let notifications = document.querySelector('.notification');
            function createToast(type, icon, title, text) {
                let newToast = document.createElement('div');
                newToast.innerHTML = `
                    <div class="toast ${type}">
                        <i class="${icon}"></i>
                        <div class="content">
                            <div class="title">${title}</div>
                            <span>${text}</span>
                        </div>
                        <i id ="cross" class="fa-solid fa-xmark" onclick="this.parentElement.remove()"></i>
                    </div>`;
                notifications.appendChild(newToast);
                newToast.timeOut = setTimeout(() => newToast.remove(), 5000);
            }

            let type = 'error'; 
            let icon = 'fa-solid fa-circle-xmark'; 
            let title = "{{ 'nameExist_title' | trans }}"; 
            let text = "{{ 'nameExist_text' | trans }}"; 

            createToast(type, icon, title, text);
        </script>
    {% endif %}

templates/partials/scriptNotif.html.twig
<div class="notification"></div>

{% if hasError %}
    <script>
        let notifications = document.querySelector('.notification');
        function createToast(type, icon, title, text) {
            let newToast = document.createElement('div');
            newToast.innerHTML = `
                <div class="toast ${type}">
                    <i class="${icon}"></i>
                    <div class="content">
                        <div class="title">${title}</div>
                        <span>${text}</span>
                    </div>
                    <i id="cross" class="fa-solid fa-xmark" onclick="this.parentElement.remove()"></i>
                </div>`;
            notifications.appendChild(newToast);
            newToast.timeOut = setTimeout(() => newToast.remove(), 5000);
        }

        let type = 'error'; 
        let icon = 'fa-solid fa-circle-xmark'; 
        let title = "{{ 'error_title' | trans }}"; 
        let text = "{{ 'error_text' | trans }}"; 

        createToast(type, icon, title, text);
    </script>
{% endif %}